spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:desafio_attus
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG